ARG GO_VERSION=0
FROM golang:${GO_VERSION}-alpine AS builder
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY go.mod ./
#COPY go.mod go.sum ./
#RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags="-s -w" -o afonsodev-api ./cmd/server

FROM scratch
WORKDIR /app
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /app/afonsodev-api .
EXPOSE 8080
ENTRYPOINT ["./afonsodev-api"]
